version: 2

jobs:
  build:
    environment: []
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

workflows:
  version: 2
  suite:
    jobs:
      - test:
          filters:
            branches:
              only:
                - imabranchwhichdoesntexist
