version: 2

jobs:
  setup:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run: yarn install
      - persist-to-workspace:
          root: .
          paths: .

  lint:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.15.1
    steps:
      - attach-workspace:
          at: ~/app/
      - run: yarn lint

  test:
    working_directory: ~/app
    docker:
      - image: circleci/node:10.15.1
    steps:
      - attach-workspace:
          at: ~/app/
      - run: yarn test

workflows:
  version: 2
  suite:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
