version: 2

jobs:
  build:
    environment:
      - TEST: true
    docker:
      - image: debian:stretch

    resource_class: xlarge

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

workflows:
  version: 2
  suite:
    jobs:
      - build:
          filters:
            branches:
              only:
                - test-branch
